name: Repo Description

on:
  push:
    branches: [ "main" ]
    paths:
      - README.md
      - .github/workflows/docker-hub.yml


jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Update Docker Repository Description
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: unlimdev/docker-stats-exporter
          short-description: ${{ github.event.repository.description }}
